[project]
name = "state-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "fastapi>=0.117.1",
    "ollama>=0.6.0",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
